<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '@@Bạn có chắc chắn muốn xóa bản ghi này không?@@',
    'Companies' => '@@Công ty@@',
    'Create' => '@@Tạo mới@@',
    'Create Company' => '@@Tạo mới công ty@@',
    'Delete' => '@@Xóa@@',
    'Reset' => '@@Làm lại@@',
    'Search' => '@@Tìm kiếm @@',
    'Update' => '@@Cập nhật@@',
    'Update {modelClass}: ' => '@@Cập nhật {modelClass}:@@',
    'Company About' => 'Giới thiệu vê công ty',
    'Company Address' => 'Địa chỉ công ty',
    'Company Email' => 'Email công ty',
    'Company Name' => 'Tên công ty',
    'Company Phone' => 'Số điện thoại',
    'ID' => 'Mã',
    'Lang ID' => 'Ngôn ngữ',
    'Website Introduct' => 'Giới thiệu website',
];
